---
- name: Setup firewall(nftables) and enable forwarding
  hosts: routers
  become: true
  vars:
    dmz_service_ip: "10.10.30.1"
    dmz_port_http:  "80"
    dmz_port_https: "443"
    admin_ip:       "192.168.60.20"
    WAN_IF:         "eth0"
    DMZ_IF:         "eth1"

  tasks:
  
    - name: Install nftables
      ansible.builtin.apt:
        name: nftables
        state: present

    - name: Copy nft rules
      ansible.builtin.template:
        src: nftables.conf.j2 
        dest: /etc/nftables.conf
        owner: root
        group: root 
        mode: '0644' 
 
    - name: Apply firewall rules
      shell: nft -f /etc/nftables.conf

    - name: Setup package forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_file: /etc/sysctl.conf
        state: present
        reload: true