---
- name: Setup firewall(iptables) and enbale forwarding
  hosts: routers
  become: true
  tasks:
  
    - name: Install iptables-persistent
      ansible.builtin.apt:
        name: iptables-persistent
        state: present

    - name: Copy ipv4 rules
      ansible.builtin.template:
        src: rules.v4.j2  
        dest: /etc/iptables/rules.ipv4
        owner: root
        group: root 
        mode: '0644' 
 
    - name: Restore firewall rules
      shell: sudo iptables-restore < /etc/iptables/rules.ipv4

    - name: Save rules persistent
      shell:   netfilter-persistent save

    - name: Setup package forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_file: /etc/sysctl.conf
        state: present
        reload: true

       