apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-external
  namespace: kube-system 
spec: 
  type: LoadBalancer    # give possibilty to stream logs from an external system
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: elasticsearch-external-slice
  namespace: kube-system  
  labels:
    kubernetes.io/service-name: elasticsearch-external # Connects this slice to elasticsearch-external above
addressType: IPv4
ports:
  - protocol: TCP
    port: 9200
endpoints:
  - addresses:
      - "10.10.60.61"
  - addresses:
      - "10.10.60.62"
  - addresses:
      - "10.10.60.63"
