apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qp-config
  namespace: qp88 # QP8 namespace
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cephfs-rw-many # Use HA Ceph filesystem
  resources:
    requests:
      storage: 10Mi # Matches vendor requirement
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qp-library
  namespace: qp88 # QP8 namespace
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: cephfs-rw-many # Use HA Ceph filesystem
  resources:
    requests:
      storage: 1Gi # Matches vendor requirement
