apiVersion: v1
kind: Secret
metadata:
  name: rook-csi-cephfs-provisioner
  namespace: rook-ceph
type: Opaque
data:
  adminID: YWRtaW4=  # This is the string 'admin' encoded in base64
  adminKey: QV*******************************==
---
apiVersion: v1
kind: Secret
metadata:
  name: rook-csi-cephfs-node
  namespace: rook-ceph
type: Opaque
data:
  adminID: YWRtaW4=  # This is the string 'admin' encoded in base64
  adminKey: QV*******************************==
